.travis.yml
src/PeclUuidFactory.php
src/Uuid.php
src/UuidFactory.php
src/UuidFactoryInterface.php
tests/PeclUuidTest.php

As suggested in #31 
Defaults to using PECL when available, fallsback to PHP factory when extension is not available, or when it is not possible to conform to the interface (parameters declared in uuid1(...) interface are not available via PECL.
Design choices (decorator instead of composing the existing factory) may be questionnable, but it gets the job done transparently, and honestly, laziness.

Add PECL based UUID factory for UUID1/4

---

src/Uuid.php

- change method "getIfconfig()" to use "passthru()" and an output buffer instead of the "backtick operator" which may be disabled for security reasons
- change  method "getNodeFromSystem()" to process detection only once per runtime - because of great performance impact
(Test: generate 100 UUIDs[v1] before ~21s / after ~200ms)

"passthru" replacement for "backtick operator" / getNodeFromSystem once per runtime 

---

src/Uuid.php

getInteger is suggesting getMostSignificantBitsHex if the math library is not available

getInteger should suggest getHex

---

README.md

Then running
composer.phar require "rhumsaa/uuid=~2.8"
said:
Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.
so should change it to 
composer.phar require "ramsey/uuid=~2.8"

composer.phar require "rhumsaa/uuid=~2.8" is not proper

---

src/FeatureSet.php
src/Generator/TimeGeneratorFactory.php
src/UuidFactory.php

- Add option to enable PeclUuidTimeGenerator via FeatureSet
- Enable use of custom TimeGenerator implementations
- Removes now unnecessary `timeConverter` and `timeProvider`
properties, setters, and getters in both FeatureSet and
UuidFactory as those are now exclusively used by the default
TimeGenerator
- Adds a `setTimeGenerator` method on UuidFactory to override the
default time generator

Time generator improvements

---

src/Converter/Number/BigNumberConverter.php

Calling the BigNumber::baseConvert method uses two consecutive convert operations:
- BigNumber::convertToBase10
- BigNumber::convertFromBase10
In BigNumberConverter's context, we can directly call each specific method to avoid
the conversion overhead (and improve performance by a very tiny little bit).

Remove unnecessary conversions in BigNumberConverter

---

src/Codec/GuidStringCodec.php
src/FeatureSet.php
tests/TestCase.php
tests/UuidTest.php

As mentionned in #75, GUID binary representations are a bit peculiar:
- On little endian (LE) architectures, the byte order of the first three fields is LE
- On big endian (BE) architectures, it is the same as a GUID
- String representation is always the same
GUID related tests had to be updated and split based on host endianness in order to assert that:
- Binary representation of a GUID is different than the UUID one on LE hosts, but string representation is the same
- Binary representation of GUIDs and UUIDs is identical on BE hosts
It's unfortunately impossible to fully test these changes on Travis CI, so you'll have to take my word that it works (or [build your own BE virtual machine](https://gist.github.com/aztech-dev/f57258e367ceb6edd100) and run the tests yourself).

Improve GUID support

---

composer.json

Just did a `composer show -i` and saw a big warning NO LONGER MAINTAINED on the ramsay/uuid package. This confused me because I was sure I switched months ago. I found out that there are still references to the old package inside the composer.json.

[2.8] Remove rhumsaa from composer.json

---

.gitattributes
.gitignore
.travis.yml
CONTRIBUTING.md
tests/src/UuidTest.php
util/build-docker-image.sh
util/run-tests.sh

The ramsey/uuid library has requirements to run on 32-bit and 64-bit systems, as well as little-endian and big-endian systems. Travis CI only provides hardware for testing 64-bit, little-endian CPU architectures, but they recently announced support for Docker[^1].
After some research, I found it is possible to use [QEMU][] with [chroot][] jails on Travis CI to emulate other CPU architectures and run tests through these chroot jails[^2]. Unfortunately, it takes an awful long time to set up a chroot jail, build PHP within it, and run the tests. It wasn't reasonable to expect to do this on every single push to the ramsey/uuid repository. This is where Docker comes in.
I was able to create chroot jails for each architecture and version of PHP combination I need to test and then turn these …

Modify Travis CI builds to run tests on multiple CPU architectures

---

src/Uuid.php
src/UuidInterface.php
tests/src/UuidTest.php

Fixes #91: Made Uuid's serializable.

---

tests/bootstrap.php
tests/src/Provider/Node/FallbackNodeProviderTest.php
tests/src/Provider/Node/RandomNodeProviderTest.php
tests/src/Provider/Node/SystemNodeProviderTest.php
tests/src/Provider/Time/FixedTimeProviderTest.php
tests/src/Provider/Time/SystemTimeProviderTest.php
tests/src/TestCase.php

- Added tests for all Providers. All tests are isolated correctness/contract/collaboration tests. 
- Moved the AspectMock teardown into the TestCase teardown. This won't affect anything that isn't using AspectMock, and will prevent forgetting to clean AspectMock when a test is over.

Test coverage providers

---

src/Provider/Node/SystemNodeProvider.php

Simplifying the method str__replace with a single call

Remove duplicated call to str_replace()

---

tests/src/Codec/GuidStringCodecTest.php

I found out these two phpDocs pointed to undefined classes. I added them as use statements.
BTW: I found this issue using my new static analysis tool [PHPStan](https://github.com/phpstan/phpstan). I can send you a PR with integrating the tool in the package's build script if you're interested :)

Fixed undefined classes in GuidStringCodecTest properties

---

src/Provider/Node/RandomNodeProvider.php
tests/src/Provider/Node/RandomNodeProviderTest.php
tests/src/Provider/Time/SystemTimeProviderTest.php

When at least one call of `mt_rand(0, 1 << 24)` in  `RandomNodeProvider::getNode()` returns `1 << 24 // 0x1000000` the method generates a hexadecimal string that contain one digit more than needed to be correct. As a result, exception 'Invalid node value' is thrown when we trying to generate UUIDv1 with `DefaultTimeGenerator`. I faced with it in practice.
Therefore, i suggest to use `0xffffff` instead of `1 << 24` to fix this behaviour.

Fix RandomNodeProvider: change the max value in mt_rand() call to prevent invalid node generation

---

src/Codec/OrderedTimeCodec.php
tests/src/Codec/OrderedTimeCodecTest.php

Fixes #117: Store UUID in an optimized way for InnoDB
Adds a Coded that extends the StringCodec. The string encoding is unchanged, but the binary output is rearranged so that it increases over time (instead of random). The UUID fields itself have not change, only the ordering. No data is lost, so decoding back will give the original string.
Example use case would be to store the data in an optimized way, but show the original UUID in the admin interface. See below for examples, if you run it, you'll see that you can convert the UUID back and forth + the binary values are increasing, as suggested by https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/
The tests should cover this also.
Example usage:
```php
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\Codec\OrderedTimeCodec;
use …
```

Codec to store UUID in an optimized way for InnoDB

---

.travis.yml

This PR
💁 For reference, see https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle.

Fix: Move operations to appropriate sections

---

tests/src/Codec/GuidStringCodecTest.php
tests/src/Codec/OrderedTimeCodecTest.php
tests/src/Codec/StringCodecTest.php
tests/src/Encoder/TimestampFirstCombCodecTest.php
tests/src/Encoder/TimestampLastCombCodecTest.php
tests/src/Generator/DefaultTimeGeneratorTest.php
tests/src/Generator/OpenSslGeneratorTest.php
tests/src/Generator/PeclUuidTestCase.php
tests/src/Generator/RandomBytesGeneratorTest.php
tests/src/Generator/SodiumRandomGeneratorTest.php
tests/src/Provider/Node/RandomNodeProviderTest.php
tests/src/TestCase.php

This PR
💁 This is the visibility as declared on the parent; there's no need to increase it.

Fix: Reduce visibility of setUp() and tearDown()

---

src/UuidFactory.php
tests/UuidFactoryTest.php
tests/UuidTest.php

Fixes https://github.com/ramsey/uuid/issues/131
- Added test cases for equals, compareTo, and fromString. 
- Added strtolower in fromString so all UUID created from a string will be converted into lowercase.

UUID equals case-insensitive

---

composer.json
tests/Generator/SodiumRandomGeneratorTest.php

This test allows the UUID library to have coverage of the collaboration between this Generator and libsodium, without the test-runner having to have that library installed. This helps improve coverage and ensure that someone doesn't break that generator and not know it because they can't run the test. 
Because this introduces a new library for function mocking, I wanted to do it as just a small PR for this one test. That library could then be used for a lot of other collaboration tests which are currently being skipped on a lot of systems, if you decide to merge this. 
(Edited for clarity)

Unit Tests: Add function mock test for systems without libsodium

---

composer.json

1.3.x is currently causing test failures when used with goaop
1.0.0-alpha2 (which we are pinned at for PHP 5.4 compat)

Pin doctrine/annotations to a 1.2.x version (Fixes build)

---

src/UuidFactory.php

Improves memory usage in `UuidFactory::uuidFromHashedName` when generating large volumes of UUID's as documented in issue #159.

Improves memory usage when generating large quantities of UUID's

---

src/Codec/StringCodec.php

I realized that 30% of the request time in our app is spent by hydrating the uuid (We are using Doctrine and in this specific request I was accidentally hydrating few thousands entities).
Luckily, I remembered the #160 and tried to do similar optimization for uuid decoding. It resulted in 10-20% performance improvement (it is not much, but every millisecond counts).
Benchmark: last commit in https://github.com/mhujer/uuid/commits/mh-uuid-decoding-speedup-benchmark
Benchmark results (Blackfire): https://blackfire.io/profiles/compare/42276a3a-cb45-47e2-80c4-61420b3c61bd/graph

Optimize UUID string decoding

---

composer.json
tests/Builder/DefaultUuidBuilderTest.php
tests/Builder/DegradedUuidBuilderTest.php
tests/Codec/GuidStringCodecTest.php
tests/Codec/OrderedTimeCodecTest.php
tests/Codec/StringCodecTest.php
tests/Encoder/TimestampFirstCombCodecTest.php
tests/Encoder/TimestampLastCombCodecTest.php
tests/Generator/CombGeneratorTest.php
tests/Generator/DefaultTimeGeneratorTest.php
tests/Generator/TimeGeneratorFactoryTest.php
tests/Provider/Node/FallbackNodeProviderTest.php
tests/UuidFactoryTest.php
tests/UuidTest.php

Fix "PHPUnit_Framework_TestCase::getMock() is deprecated" warnings

---

composer.json

It is not necessary anymore, because the minimal required version was already set to 7.0

Drop paragonie/random_compat from dependencies

---

phpunit.xml.dist

- added XSD schema, so it can be validated (and PHPStorm provides
auto-completion)
- dropped backupGlobals option, because false is the default value

Add XSD schema to phpunit.xml.dist config

---

.travis.yml
src/Provider/Node/SystemNodeProvider.php
tests/Provider/Node/SystemNodeProviderTest.php

Linux offers a sysfs interface to the mac addresses of the network
interfaces without calling exec. this fixes #184
This enables repeatable system based UUID generation even on docker images
like php:7 
TODO:

Add feature to use sysfs interface to get node identifier

---

.travis.yml
composer.json
phpstan-tests.neon
phpstan.neon
src/BinaryUtils.php
src/Converter/Time/GmpTimeConverter.php
src/FeatureSet.php
src/Provider/Time/FixedTimeProvider.php
src/Uuid.php
tests/Codec/GuidStringCodecTest.php
tests/Codec/OrderedTimeCodecTest.php
tests/Codec/StringCodecTest.php
tests/Converter/Time/PhpTimeConverterTest.php
tests/Encoder/TimestampLastCombCodecTest.php
tests/Generator/DefaultTimeGeneratorTest.php
tests/Generator/SodiumRandomGeneratorTest.php
tests/Provider/Node/SystemNodeProviderTest.php
tests/UuidTest.php

[PHPStan](https://github.com/phpstan/phpstan) is a PHP Static Analysis Tool.
I've fixed the errors it can find up to level 2 (it has 7 levels of checks), but this PR is already big enough, so I will create another one later on.

[4.x] Add PHPStan analysis to the build

---

tests/Codec/OrderedTimeCodecTest.php
tests/Provider/Node/SystemNodeProviderTest.php
tests/UuidFactoryTest.php
tests/UuidTest.php
tests/Validator/ValidatorTest.php

It helps with refactorings and static analysis, because you can easily tell if the class is referenced or not.

[4.x] Use ::class constants where possible

---

tests/Provider/Node/RandomNodeProviderTest.php

Tests cannot be ran on 32bit build on Windows, because of the int overflow.
----
I also think that an exception should be added to `RandomNodeProvider::getNode()` on 32bit system, in case someone uses it accidentally, because it provides less randomness than expected:
See output from https://3v4l.org/SJiKq
```
string(12) "ffca431bbc02"
string(12) "57826953df77"
string(12) "c1ec83806b01"
string(12) "a50d6a523e4f"
string(12) "2597f3adf7b3"
string(12) "1f935e5cfca6"
```
And from my local PHP _(PHP 7.1.12 (cli) (built: Nov 23 2017 04:33:43) ( NTS MSVC14 (Visual C++ 2015) x86 )_. Note the leading zeros:
```
string(12) "00003e573b8b"
string(12) "0000363534d3"
string(12) "00005dd23a9a"
string(12) "0000a7788b66"
string(12) "0000af510161"
string(12) "000082e3e0af"
```

RandomNodeProviderTest can run only on 64bit

---

src/Generator/DefaultTimeGenerator.php
tests/Generator/DefaultTimeGeneratorTest.php

An unrelated fix for an off-by-one error I spotted while studying your code. 16384 is actually the first 15-bit integer and [is out of spec](https://tools.ietf.org/html/rfc4122#section-4.2.2). I've changed the format to hexadecimal to emphasize where the bit width ends.
Also replaced `mt_rand` with `random_int`. Even though the library targets PHP 5.4 it already required `paragonie/random_compat` so it was already available for all versions below 7.0.

Fix for DefaultTimeGenerator

---

src/Provider/Node/SystemNodeProvider.php
tests/Provider/Node/SystemNodeProviderTest.php

As stated in [the accompanying issue](https://github.com/ramsey/uuid/issues/187), the tests for the SystemNodeProvider class suffer from the "Subclass To Test" anti-pattern by mocking the class under test.
This merge request fixes that.
Besides a minor change in the class itself, this MR focuses exclusively on the test:
- The class under test is no longer mocked, instead the native PHP functions are mocked (using the already present AspectMock).
- Documentation is added to the test class to make it's purpose more clear.
- The main test case has been expanded with a data-provider that offers more descriptive examples of the input the class under test is expected to parse.
- Two new classes (and data-providers) have been added for negative scenario's.
- The methods in the test class have …

Improvements to the SystemNodeProviderTest class

---

composer.json

This deals with #142 by adding a polyfil for the ctype functions instead of failing an install.
The only downside for end users is that their version is slightly slower if it is ran without ctype. But it does allow them to run it, instead of  not allowing the composer install.
I can understand not wanting to add a new dependency to the project, especially if it is only to support one edge-case on one function.
I can also add the following snippet to this project instead, since xdigit is the only ctype function in use.
```php
if(!function_exists('ctype_xdigit')) {
/**
* Returns TRUE if every character in text is a hexadecimal 'digit', that is a decimal digit or a character from [A-Fa-f] , FALSE otherwise.
*
* @see http://php.net/manual/en/function.ctype-xdigit.php
*
* @param string|int …
```

Add a polyfill for ctype

---

src/Uuid.php
tests/UuidTest.php

A simple change to disallow UUIDs with a trailing newline, which IMO should not be valid (**please correct me if I'm wrong here!**).
This change updates the regex to use the PCRE_DOLLAR_ENDONLY modifier so that it matches only if it's the end of the string.
> D (PCRE_DOLLAR_ENDONLY)
If this modifier is set, a dollar metacharacter in the pattern matches only at the end of the subject string. Without this modifier, a dollar also matches immediately before the final character if it is a newline (but not before any other newlines). This modifier is ignored if m modifier is set. There is no equivalent to this modifier in Perl.
From http://php.net/manual/en/reference.pcre.pattern.modifiers.php

Don't allow UUIDs to have trailing newline

---

composer.json

v9.99.99 of random_compat is a no-op library specifically for PHP7.

Support random_compat v9.99.99

---

composer.json
phpstan-tests.neon
phpstan.neon
src/Generator/DefaultTimeGenerator.php
src/Generator/RandomLibAdapter.php
src/Provider/Node/FallbackNodeProvider.php
tests/Codec/GuidStringCodecTest.php
tests/Codec/OrderedTimeCodecTest.php
tests/Codec/StringCodecTest.php
tests/Generator/DefaultTimeGeneratorTest.php

* resolved #207
* switched from phpstan/phpstan-shim to phpstan/phpstan,
* adjusted the composer script to behave nicely on gitbash/travis etc.
* bumped up some of the phpstan levels, resolved issues.
a phpdoc block in moontoast/math is holding up level 6: https://github.com/ramsey/moontoast-math/blob/c2792a25df5cad4ff3d760dd37078fc5b6fccc79/src/Moontoast/Math/BigNumber.php#L633 , i.e. BigNumber is being passed in when the docs specify string|int

4.x  phpstan

---

src/Provider/Node/SystemNodeProvider.php
tests/Provider/Node/SystemNodeProviderTest.php

I noticed that the system node part of the UUID was always random on our FreeBSD systems.  After reviewing the code I see that `SystemNodeProvider` uses the output of `php_uname` to determine the OS it's running on.
It doesn't specifically test for FreeBSD, and the default uses a `netstat` command that isn't supported on FreeBSD.
I have updated `SystemNodeProvider` to check for FreeBSD specifically and have included a `net stat` command that will provide output such as the following:
```
Name    Mtu Network       Address              Ipkts Ierrs Idrop    Opkts Oerrs  Coll
em0    1500 <Link#1>      08:00:27:71:a1:00    65514     0     0    42918     0     0
em1    1500 <Link#2>      08:00:27:d0:60:a0     1199     0     0      535     0     0
lo0   16384 <Link#3>      lo0 …
```

Add support for determining MAC address on FreeBSD systems

---

composer.json
tests/bootstrap.php

Broken because of new version of [goaop/framework was released](https://github.com/goaop/framework/releases).
Ref https://github.com/ramsey/uuid/pull/210#discussion_r168399987
EDIT: Depends on https://github.com/ramsey/uuid/pull/214

Tests: configure cacheDir for AspectMock

---

src/DegradedUuid.php
src/Uuid.php
src/UuidInterface.php
tests/UuidTest.php

This PR solves this issue https://github.com/ramsey/uuid/issues/222
Apart from that, I have changed a little bit the test to improve it, like using the const `::class` instead of the hardcoded string, removing unused returned objects and a few more improvements.

Change getDateTime to DateTimeInterface

---

src/Provider/Node/SystemNodeProvider.php

Bug Fixes #240 
PHP_OS predefined constant was used instead of php_uname() function.

PHP_OS predefined constant was used instead of php_uname() function.

---

.gitattributes
.travis.yml
composer.json
phpcs.xml.dist
psalm.xml
src/Uuid.php
src/UuidInterface.php
static-analysis/UuidIsImmutable.php

This patch adds `@psalm-immutable` to `UuidInterface`, and marks the named constructors of `Uuid` as `@psalm-pure` too.
This is very similar to https://github.com/moneyphp/money/pull/576 in spirit and implementation
UUIDs are identifiers that cross serialization and address space boundaries, and should be treated as immutable values.
A new `static-analysis` (not exported) directory has been created: it includes fixtures that are verifying the transitivity of the added `@psalm-pure` and `@psalm-immutable` type invariant markers.
Please note that this will cause type changes for downstreams implementors (custom implementations) of `UuidInterface` that do use `vimeo/psalm`: if their code does not follow `@psalm-immutable` invariants, they will get a build failure. No runtime behavior changes …

Minimal UUID immutability invariants at type-level

---

.gitattributes
psalm-baseline.xml
psalm.xml
src/BinaryUtils.php
src/Codec/GuidStringCodec.php
src/Codec/OrderedTimeCodec.php
src/Converter/Time/PhpTimeConverter.php
src/DegradedUuid.php
src/Uuid.php
src/UuidFactory.php

Adds [Psalm](https://psalm.dev/) Static Analysis checks to cover src folder, in addition to the `static-analysis` folder which @Ocramius recently added.
This changes the psalm xml config to make it include the `src` folder, and also uses the psalm 'baselining' feature to make Psalm ignore all existing errors (or apparent errors) that it detected when run on my machine.
A great follow-up project would be to go through those errors and fix them one-by-one, or in cases where they can't or shouldn't be fixed suppress them using an inline code comment and add some more information. In the meantime having this merged and keeping the build green will prevent any additional errors that Psalm can detect getting in.
Psalm is already run as part of the Travis config.

Run Psalm on src as well as Static Analysis Fixture

---

src/Codec/TimestampFirstCombCodec.php

Just fixing a typo I've just seen in a phpdoc.
This PR doesn't change anything at all.

Fix typo in TimestampFirstCombCodec

---

src/Codec/CodecInterface.php
src/Codec/OrderedTimeCodec.php
src/Codec/StringCodec.php
src/Codec/TimestampFirstCombCodec.php
src/Converter/Number/GenericNumberConverter.php
src/Converter/NumberConverterInterface.php
src/Uuid.php
src/UuidInterface.php
tests/static-analysis/UuidIsNeverEmpty.php

Overall, we know that a UUID can never be an empty string, hex, or numeric string. Even the zero-case is `'0'` in hex/int stringy form.
This patch formalizes that, allowing consumers of `UuidInterface` to rely on the fact that the produced `string` will never be empty.
Additional static-analysis tests were introduced: they just check variance.

Refining type of producing a `string` that can be declared as `non-empty-string`

---

docs/database.rst
docs/upgrading/3-to-4.rst

Fixes a couple minor typos in (excellent) the project documentation.
https://twitter.com/ramsey/status/1238959284068782080
Visual testing only

Fix Minor Typos in Docs

---

src/Builder/DegradedUuidBuilder.php
src/Builder/FallbackBuilder.php
src/Builder/UuidBuilderInterface.php
src/Generator/DefaultNameGenerator.php
src/Generator/NameGeneratorInterface.php
src/Generator/PeclUuidNameGenerator.php
src/Guid/GuidBuilder.php
src/Nonstandard/UuidBuilder.php
src/Rfc4122/UuidBuilder.php
src/Uuid.php
src/UuidFactory.php
src/UuidFactoryInterface.php
tests/psalm-baseline.xml
tests/static-analysis/UuidIsImmutable.php

`Uuid::uuid5()` can be safely used within the context of pure functions, as it guarantees same output for same parameters.
Added static analysis tests.

Marking `Uuid::uuid5()` as pure: same input leads to same output, and no I/O under normal operational constraints

---

tests/Codec/GuidStringCodecTest.php
tests/Codec/OrderedTimeCodecTest.php
tests/Codec/StringCodecTest.php
tests/Generator/CombGeneratorTest.php
tests/Generator/PeclUuidRandomGeneratorTest.php
tests/Generator/PeclUuidTimeGeneratorTest.php
tests/Generator/RandomBytesGeneratorTest.php
tests/Generator/RandomLibAdapterTest.php
tests/Guid/FieldsTest.php
tests/Nonstandard/FieldsTest.php
tests/Provider/Node/FallbackNodeProviderTest.php
tests/Provider/Node/SystemNodeProviderTest.php
tests/Rfc4122/FieldsTest.php
tests/UuidFactoryTest.php
tests/UuidTest.php

All occurrences of `assertEquals` have been replaced with `assertSame`.
*Assert equals* coerces types if they are different whereas *assert same* never performs type coercion. The differences are similar to the differences between loose comparison (`==`) and strict comparison (`===`). 
For the same reason that strict quality (`===`) is always preferred over loose quality (`==`), *assertSame* should always be preferred over *assertEquals* because *assertEquals* can mask bugs and provide false positives. Having made the changes, it seems there were no such false positives, but we can only be sure since making this change.
In some cases, *assertEquals* was inspecting private members of objects to perform equality comparisons, such as in the following example. …

Use assertSame instead of assertEquals

---

src/Builder/BuilderCollection.php
src/Builder/DefaultUuidBuilder.php
src/Guid/Guid.php
src/Nonstandard/Uuid.php
src/Provider/Node/NodeProviderCollection.php

Several classes implement interfaces already specified by the base class they are extending. Such specifications are redundant and can be safely removed.
As above.
Code cleanup.
Run tests locally.

Removed redundant interface speficiation

---

tests/Generator/CombGeneratorTest.php

Using PHPUnit 9
```
1) Ramsey\Uuid\Test\Generator\CombGeneratorTest::testGenerateWithOddNumberOverTimestampBytesCausesError
Support for using expectException() with PHPUnit\Framework\Error\Error is deprecated and will be removed in PHPUnit 10. Use expectError() instead.
```
`expectError` already exists in PHPUnit 8

use expectError instead of expectException

---

src/Generator/DefaultNameGenerator.php

Using PHPUnit  9 and PHP 8.0.0RC3
There was 1 failure:
```
1) Ramsey\Uuid\Test\Generator\DefaultNameGeneratorTest::testGenerateThrowsException
Failed asserting that exception of type "ValueError" matches expected exception "Ramsey\Uuid\Exception\NameException". Message was: "hash(): Argument #1 ($algo) must be a valid hashing algorithm" at
/dev/shm/BUILDROOT/php-ramsey-uuid-4.1.1-1.fc31.remi.x86_64/usr/share/php/Ramsey/Uuid/Generator/DefaultNameGenerator.php:33
/dev/shm/BUILD/uuid-cd4032040a750077205918c86049aa0f43d22947/tests/Generator/DefaultNameGeneratorTest.php:78
```

catch ValueError raised by PHP 8

---

composer.json

Allow installation of `paragonie/random_compat` version 9.99.100 to avoid downgrades to version 2.x when upgrading a project to PHP 8.
`paragonie/random_compat` 9.99.99 is not compatible with PHP 8, but 9.99.100 is, see [`v9.99.99...v9.99.100`#diff-d2ab9925ca](https://github.com/paragonie/random_compat/compare/v9.99.99...v9.99.100#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34)
`composer require 'ramsey/uuid:^3.8'` with PHP 8 installs `paragonie/random_compat` in the wrong version (`2.0.19` instead of `9.99.99`)

Allow install of paragonie/random_compat 9.99.100

---

src/Uuid.php
tests/Codec/OrderedTimeCodecTest.php

The change in https://github.com/ramsey/uuid/issues/318 is the root cause of issues https://github.com/ramsey/uuid/issues/329 and https://github.com/ramsey/uuid-doctrine/issues/152. This PR should fix that.
The  problem is, that call to `getBytes` and subsequently `this->codec->encodeBytes` returns invalid result when UUID is used with `OrderedTimeCodec`. When this combination is used, current master returns binary string with shuffled values (as OrderedTimeCodec does) and deserialization later returns invalid instance of UUID. Then new code is same as would `StringCodec` do.
Fixed https://github.com/ramsey/uuid/issues/329 and https://github.com/ramsey/uuid-doctrine/issues/152
Unit test included

Serialization should not use internal codec

---

src/Uuid.php
tests/UuidTest.php

The `$uuid` parameter on `Uuid::fromString()` [was changed from `string` to `non-empty-string`](https://github.com/ramsey/uuid/commit/c005f69d6e5c16a807093d693ed1dbdf730b3c67#diff-898c45cfd882f04a4877c82e14ce28181f8ea6062654772bfb9fc474014bd6a0R439) this breaks BC for people using static analysis in their downstream projects.
I've reverted the change to the docblock and used an assertion to teach static analysis tools when the `$uuid` variable is a non empty string instead.
Whilst this isn't a language level backwards compatibility break, it does break when consumers are using static analysis tools on their own code base because they'd need to add checks to test if the input is non empty before calling `Uuid::fromString()`.
I've added a unit test covering the call to …

Fix soft BC break with `Uuid::fromString()` signature

---

.github/workflows/continuous-integration.yml
composer.json
phpstan.neon.dist
psalm-baseline.xml
src/Fields/SerializableFieldsTrait.php
src/Lazy/LazyUuidFromString.php
src/Type/Decimal.php
src/Type/Hexadecimal.php
src/Type/Integer.php
src/Type/Time.php
src/Uuid.php

This PR gets this library working on PHP 8.1. The new PHP 7.4 style serialisation is now mandatory, from PHP 8.1 onwards. I've checked that the two incompatible serialisation formats are in fact compatible. The old style can be deserialized just fine: https://3v4l.org/XfUS3. This means upgrading is easy and no risk. On PHP 7.2 and 7.3, there are no changes. On PHP 7.4+, the old style gets deserialized properly, and going forward, the new style will be used for serialisation.

Add support for PHP 8.1

---

src/Uuid.php
tests/UuidTest.php

This pull request tries to improve the Uuid::fromString static class by creating LazyUuidFromString even for UUID string which are not lowercase.
This pull request solves discrepancy of returning LazyUuidFromString for UUIDs, which are not in lower case. LazyUuidFromString::VALID_REGEX is case sensitive, so only UUID strings in lower case are accepted. In the same time, the function strtolower() is called in constructor parameter, but the if statement already accepted only strings in lowercase. Thus calling the strtolower on string in lowercase is redundant.
I updated the method so it lowers the string first and then tries to match the regexp. If it is valid uuid string according to the regexp, then instance of LazyUuidFromString is returned. Otherwise the functionality is not affected. …

LazyUuidFromString for valid UUIDs in uppercase

---

.gitattributes
.github/dependabot.yml
.github/workflows/continuous-integration.yml
.github/workflows/merge-dependabot-upgrades.yml
.gitignore
composer.json
composer.lock
psalm.xml
src/Generator/CombGenerator.php
src/Provider/Dce/SystemDceSecurityProvider.php
tests/Provider/Node/SystemNodeProviderTest.php

* targets **4.3.0**
* drop all polyfills
* upgrade the requirement to PHP 8.0
* require `ext-ctype` to be installed
* lock dependencies to their latest version
* improve @dependabot automation to reduce maintenance burden on @ramsey's side
The main change here is the dropping of `symfony/polyfill*` dependencies: these dependencies are supposed to be installed by consumers, and not by libraries. If libraries start requiring the polyfills, they:
1. become a dependency in the dependency graph, increasing ecosystem complexity
2. shadow actual functionality that might need to be enabled on target systems (i.e. "works best with ext-ctype")
3. introduce a dependency to an ecosystem that is highly unstable (bad track record of `symfony/*` packages and their supported version ranges)
While …

Bump to PHP 8.0, remove polyfills, require ext-ctype, lock dependencies, improve dependency upgrade automation
