ramsey/uuid

- .gitignore
Just added the PHPStorm IDE directory to the ignore list.
> Added PHPStorm to ignore

- src/BinaryUtils.php
- src/FeatureSet.php
- src/Generator/DefaultTimeGenerator.php
- src/Generator/PeclUuidRandomGenerator.php
- src/Generator/PeclUuidTimeGenerator.php
- src/Generator/TimeGeneratorFactory.php
- src/Generator/TimeGeneratorInterface.php
- src/UuidFactory.php
- tests/UuidTest.php
- Remove UuidFactory from signature
- Remove setters on UuidFactory to prevent inconsistencies (a new feature set and factory should be used instead)
- Update tests to reflect those changes
> Refactor TimeGeneratorInterface

- src/BinaryUtils.php
- src/FeatureSet.php
- src/Generator/DefaultTimeGenerator.php
- src/Generator/PeclUuidRandomGenerator.php
- src/Generator/PeclUuidTimeGenerator.php
- src/Generator/TimeGeneratorFactory.php
- src/Generator/TimeGeneratorInterface.php
- src/UuidFactory.php
- tests/UuidTest.php
This isn't the most elegant solution for abstracting time generation into a `TimeGeneratorInterface` family of classes, but it works as a proof-of-concept for what I'd like to do.
Please feel free to submit pull requests to my `pecl-generator` branch to make this better.
> Random and time generators for pecl-uuid

- src/Codec/StringCodec.php
- src/FeatureSet.php
- src/Generator/DefaultTimeGenerator.php
- src/Provider/Time/FixedTimeProvider.php
- src/Uuid.php
@ramsey requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/ramsey/uuid/
> Scrutinizer Auto-Fixes

- src/Converter/Number/DegradedNumberConverter.php
- src/Converter/Time/DegradedTimeConverter.php
- tests/UuidTest.php
> Fix exception message assertion in tests

- src/Uuid.php
- tests/UuidTest.php
As mentionned in #76, targeting 2.8 branch
> Fix exception message assertion

- composer.json
Changed old support location to new support location.
> [3.0] Removed rhumsaa locations from composer.json

- src/Builder/DefaultUuidBuilder.php
- src/Builder/DegradedUuidBuilder.php
- src/Codec/GuidStringCodec.php
- src/Codec/StringCodec.php
- src/DegradedUuid.php
- src/FeatureSet.php
- src/Provider/Time/FixedTimeProvider.php
- src/Uuid.php
- src/UuidFactory.php
- src/UuidInterface.php
Just a bit of house keeping for the sake of code cleanliness.
> Cleanup: Update and add missing docblocks, remove unused imports

- .travis.yml
- composer.json
- src/Console/Command/DecodeCommand.php
- tests/Console/Command/DecodeCommandTest.php
- tests/Console/Command/GenerateCommandTest.php
See puli/discovery#19 for discussion
> Added support for symfony/console v3

- CHANGELOG.md
- composer.json
- src/Uuid.php
- tests/UuidTest.php
Fixes issue #80 for the 2.x series
> Drop OpenSSL support and use paragonie/random_compat

- tests/src/Generator/PeclUuidRandomGeneratorTest.php
- tests/src/Generator/PeclUuidTimeGeneratorTest.php
- tests/src/UuidTest.php
> Fix: Remove unused imports

- tests/src/Builder/DefaultUuidBuilderTest.php
- tests/src/Builder/DegradedUuidBuilderTest.php
- tests/src/Codec/GuidStringCodecTest.php
- tests/src/Codec/StringCodecTest.php
- tests/src/Converter/Number/DegradedNumberConverterTest.php
- tests/src/Converter/Time/PhpTimeConverterTest.php
- tests/src/Generator/CombGeneratorTest.php
- tests/src/Generator/MtRandGeneratorTest.php
- tests/src/Generator/OpenSslGeneratorTest.php
- tests/src/Generator/PeclUuidRandomGeneratorTest.php
- tests/src/Generator/PeclUuidTestCase.php
- tests/src/Generator/PeclUuidTimeGeneratorTest.php
- tests/src/Generator/RandomBytesGeneratorTest.php
- tests/src/Generator/RandomLibAdapterTest.php
- tests/src/Generator/TimeGeneratorFactoryTest.php
- tests/src/TestCase.php
- Added isolated tests for Codecs
- added `@covers` annotations on these and all of the existing isolated tests I've worked on so far
- small test clean up of duplicated tear down methods on other test files
> Test coverage Codec

- src/Provider/Node/SystemNodeProvider.php
- tests/src/Provider/Node/SystemNodeProviderTest.php
> 107 cache system node provider

- README.md
- composer.json
- src/Builder/DefaultUuidBuilder.php
- src/Builder/DegradedUuidBuilder.php
- src/Converter/Number/GmpConverter.php
- src/Converter/Time/BigNumberTimeConverter.php
- src/Converter/Time/DegradedTimeConverter.php
- src/Converter/Time/GmpTimeConverter.php
- src/Converter/TimeConverterInterface.php
- src/DegradedUuid.php
- src/FeatureSet.php
- src/Uuid.php
- tests/src/Builder/DefaultUuidBuilderTest.php
- tests/src/Builder/DegradedUuidBuilderTest.php
- tests/src/Converter/Time/DegradedTimeConverterTest.php
- tests/src/TestCase.php
- tests/src/UuidTest.php
> Add GmpConverter and GmpTimeConverter

- tests/UuidFactoryTest.php
Just adding some additional coverage, a little at a time. Getters/Setters are easy to test, so why not :)
> Adding test coverage for getters/setters currently untested.

- composer.json
We do not support PHP6 nor PHP8.
> Be more specific about PHP versions

- src/Codec/StringCodec.php
- src/Exception/InvalidUuidStringException.php
- tests/UuidTest.php
This should solve #161 
I didn't add anything to CHANGELOG.md since I'm not sure which release will contain this change.
> add a specific exception for invalid UUID string

- src/Uuid.php
- tests/UuidTest.php
I suggested an enhancement, but after reading the contribution guide I've decided to implement it myself in three flavors (so you can decide which is better, and eventually merge). All of them are tested.
This one is perhaps the most simple one. I've just added 5 constants into Uuid class, and tests for them.
Thx
> issue #173 expose versions alternative1

- src/Provider/Node/RandomNodeProvider.php
- tests/Provider/Node/RandomNodeProviderTest.php
When merged, this will close #171 and close #170.
> Set the multicast bit for random nodes, according to RFC 4122, §4.5

- composer.json
> Bumps `phpunit/phpunit` development dependency to version 6.4

- .gitattributes
Added `.md` files and the docs directory to be excluded in production.
> Exclude docs from production

- composer.json
This should make the build green again.
> Do not use the latest goaop/framework 2.2

- composer.json
- tests/TestCase.php
> Use class-based PHPUnit namespace

- docs/database.rst
- docs/faq.rst
- docs/nonstandard.rst
- docs/nonstandard/guid.rst
- docs/nonstandard/version6.rst
- docs/rfc4122/version2.rst
- docs/upgrading/3-to-4.rst
Quick proofread of the documentation
Request on twitter =)
Reading :man_shrugging:
> Fix small issues with docs

- composer.json
Remove unnecessary dev dependency from composer. 
Fixes #313
> Remove phpstan/phpdoc-parser from dev dependencies

- composer.json
Add support for brick/math ^0.9
> Add support for brick/math ^0.9

- src/Builder/BuilderCollection.php
- src/Provider/Node/NodeProviderCollection.php
- tests/phpstan-tests.neon
Fix static analysis issues
All CI workflows should be passing
`composer run-script test`
> Fix static analysis issues

- .github/dependabot.yml
RE: https://twitter.com/Ocramius/status/1474179909157273601
from
https://twitter.com/ramsey/status/1474178806923595778
I'd like to see dependabot offer a suggestion for upgrading the action like Ocramius suggested; it might have broader impact than just solving the upgrade.
It's from GitHub docs, and modifies their example frequency to match your composer frequency. I Figure if you don't want to be bombarded daily or weekly with composer; I should probably modify their example to be the same frequency rather than in-tandem advocating to spend more of your time on maintenance.
I don't believe the PR checklist applies as this is declarative config yaml; but feel free to correct me; Merry Christmas and a Happy New Year
> Use dependabot to suggest updates to all actions

- .github/workflows/continuous-integration.yml
I mostly want to check if dependabot suggests this change after #395 or if it does more. Please lets see if #395 suggests this 🙏 
You asked for this 😉 https://twitter.com/ramsey/status/1474178806923595778
GitHub actions should run this (I think you may need to allow that)
Not sure this last section applies. Feel free to let me know if it does.
> Use version 2 of ramsey/composer-install
